# -*- mode: python ; coding: utf-8 -*-

hiddenimports = [
    "app_info",
    "bitmap",
    "constants",
    "crc32c",
    "debuglog",
    "directory",
    "dnd",
    "extents",
    "fuse_mount",
    "gui",
    "hashdir",
    "host",
    "inode",
    "io_backend",
    "journal",
    "partitions",
    "superblock",
    "system_raw_helper",
    "usbdk_backend",
    "usbdk_setup",
    "volume",
    "windows_disk",
    "winfsp_setup",
    "writer",
    "fuse",
    "tkinter",
    "tkinter.ttk",
    "tkinter.filedialog",
    "tkinter.messagebox"
]

a = Analysis(
    ["main.py"],
    pathex=["."],
    binaries=[],
    datas=[],
    hiddenimports=hiddenimports,
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=[],
    noarchive=False,
)
pyz = PYZ(a.pure)

exe = EXE(
    pyz,
    a.scripts,
    a.binaries,
    a.zipfiles,
    a.datas,
    [],
    name="Ext4Reader",
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=False,
    upx_exclude=[],
    runtime_tmpdir=None,
    console=False,
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
)
